version: 2

jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test TheConsultancyFirm.Tests
